Repository input-output-hk/rust-cardano, pull requests merged in 2018-10, with the labels that each got.

#278 Fix bad input selection in some rare cases
  cardano/src/fee.rs
  cardano/src/input_selection.rs
  cardano/src/tx.rs
  cardano/src/txbuild.rs
Labels: B - Bug, P - high

#279 Update README.md
  README.md
Labels: P - low

#280 Error display fixes
  cardano/src/wallet/rindex.rs
Labels: D - easy, P - low

#281 add a new test for the hdwallet derivation
  cardano/src/hdwallet.rs
Labels: D - medium, P - low

#283 introduce quickcheck property testing
  Cargo.lock
  cardano/Cargo.toml
  cardano/src/coin.rs
  cardano/src/lib.rs
Labels: D - easy, P - low

#282 Update input selection policy
  cardano/Cargo.toml
  cardano/src/bip/bip39.rs
  cardano/src/coin.rs
  cardano/src/fee.rs
  cardano/src/hdwallet.rs
  cardano/src/input_selection.rs
  cardano/src/input_selection/mod.rs
  cardano/src/input_selection/simple_selections.rs
  cardano/src/lib.rs
  cardano/src/txutils.rs
  cardano/src/util/arbitrary.rs
  cardano/src/util/mod.rs
  cardano/src/wallet/bip44.rs
  cardano/src/wallet/rindex.rs
  cardano/src/wallet/scheme.rs
Labels: D - medium, P - high

#287 Make blackjack a bit random so we have a proper implementation of the algo
  cardano/src/input_selection/simple_selections.rs
Labels: D - medium

#288 Add Output Policy error and handle the impossible output policy case
  cardano/src/txbuild.rs
  cardano/src/wallet/scheme.rs
Labels: B - Bug, P - high

#291 Genesis block rename
  cardano/src/block/block.rs
  cardano/src/block/boundary.rs
  cardano/src/block/mod.rs
  cardano/src/block/verify.rs
  cardano/src/block/verify_chain.rs
  exe-common/src/network/hermes.rs
  exe-common/src/sync.rs
  storage/src/block/iter.rs
  storage/src/epoch.rs
  storage/src/lib.rs
  storage/src/utxo.rs
Labels: X - code-structure

#295 in the input selection, accept the extra coin lost
  cardano/src/input_selection/mod.rs
Labels: B - Bug, D - medium, P - high

#296 remove the loop and simply use the modulo of the MAX_COIN
  cardano/src/util/arbitrary.rs
Labels: P - low

#297 Add travis CI for windows (potentially remove appveyor?)
  .travis.yml
Labels: X - question

#306 rustfmt pass
  .travis.yml
  protocol-tokio/examples/client.rs
  protocol-tokio/examples/server.rs
  protocol-tokio/src/lib.rs
  protocol-tokio/src/network_transport/accepting.rs
  protocol-tokio/src/network_transport/closing.rs
  protocol-tokio/src/network_transport/connecting.rs
  protocol-tokio/src/network_transport/event.rs
  protocol-tokio/src/network_transport/mod.rs
  protocol-tokio/src/network_transport/response_code.rs
  protocol-tokio/src/protocol/accepting.rs
  protocol-tokio/src/protocol/codec/handshake.rs
  protocol-tokio/src/protocol/codec/message.rs
  protocol-tokio/src/protocol/codec/mod.rs
  protocol-tokio/src/protocol/codec/node_id.rs
  protocol-tokio/src/protocol/connecting.rs
  protocol-tokio/src/protocol/inbound_stream.rs
  protocol-tokio/src/protocol/mod.rs
  protocol-tokio/src/protocol/outbound_sink.rs
  protocol/src/ntt/mod.rs
  protocol/src/ntt/protocol.rs
  protocol/src/packet.rs
  protocol/src/protocol.rs
  storage-units/src/append.rs
  storage-units/src/hash.rs
  storage-units/src/indexfile.rs
  storage-units/src/lib.rs
  storage-units/src/packfile.rs
  storage-units/src/reffile.rs
  storage-units/src/utils/bitmap.rs
  storage-units/src/utils/bloom.rs
  storage-units/src/utils/directory_name.rs
  storage-units/src/utils/error.rs
  storage-units/src/utils/lock.rs
  storage-units/src/utils/magic.rs
  storage-units/src/utils/mod.rs
  storage-units/src/utils/serialize.rs
  storage-units/src/utils/tmpfile.rs
  storage/src/config.rs
  storage/src/epoch.rs
  storage/src/iter/epoch.rs
  storage/src/iter/mod.rs
  storage/src/iter/range.rs
  storage/src/iter/reverse.rs
  storage/src/lib.rs
  storage/src/pack.rs
  storage/src/refpack.rs
  storage/src/tag.rs
  storage/src/types.rs
  storage/src/utxo.rs
Labels: X - code-structure
