Repository input-output-hk/rust-cardano, pull requests merged in 2018-04, with the labels that each got.

#22 [DDW-174] also run js test suite on travis
  .travis.yml
Labels: D - easy, P - high

#36 use a slice instead of a string for the `CONST` in paperwallet
  wallet-crypto/src/paperwallet.rs
Labels: P - low, X - WIP

#35 prepare npm release 0.1.2
  package-lock.json
  package.json
Labels: X - WIP
